# Generated by Django 4.2.11 on 2024-04-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TokenAuth",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=40, verbose_name="token")),
                (
                    "contact_persoon",
                    models.CharField(
                        help_text="De naam van de contact persoon van de organisatie die gebruik mag maken van de API.",
                        max_length=200,
                        verbose_name="contact persoon",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="De email van de oranisatie die gebruik mag maken van de API.",
                        max_length=254,
                        verbose_name="email",
                    ),
                ),
                (
                    "afdeling",
                    models.CharField(
                        blank=True,
                        help_text="De afdeling van de organisatie die gebruik mag maken van de API.",
                        max_length=200,
                        verbose_name="afdeling",
                    ),
                ),
                (
                    "organisatie",
                    models.CharField(
                        blank=True,
                        help_text="De organisatie die gebruik mag maken van de API",
                        max_length=200,
                        verbose_name="organisatie",
                    ),
                ),
                (
                    "laatst_aangepast",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="De laatste datum dat de token aangepast was.",
                        verbose_name="laatst aangepast",
                    ),
                ),
                (
                    "aangemaakt",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="De datum wanneer de token was aangemaakt.",
                        verbose_name="created",
                    ),
                ),
                (
                    "applicatie",
                    models.CharField(
                        blank=True,
                        help_text="De applicatie die gebruik mag maken van de API.",
                        max_length=200,
                        verbose_name="application",
                    ),
                ),
                (
                    "administratie",
                    models.CharField(
                        blank=True,
                        help_text="De administratie die gebruik mag maken van de API.",
                        max_length=200,
                        verbose_name="administration",
                    ),
                ),
            ],
            options={
                "verbose_name": "token authorizatie",
                "verbose_name_plural": "token authorizaties",
            },
        ),
    ]
