openapi: 3.0.3
info:
  title: Referentielijsten API
  version: 1.0.0
  description: Een API om de informatie op te halen van stam tabellen
  contact:
    url: https://github.com/maykinmedia/referentielijsten
  license:
    name: EUPL
    url: https://github.com/maykinmedia/referentielijsten/blob/master/LICENSE.md
paths:
  /tabel:
    get:
      operationId: gettabelen
      description: De operatie waarmee alle gegevens van een tabel wordt opgehaald.
      parameters:
      - in: query
        name: code
        schema:
          type: string
      - in: query
        name: geldig
        schema:
          type: boolean
        description: Zoek klantcontacten met specifieke tekst in inhoud
      tags:
      - tabelen
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Tabel'
          description: ''
components:
  schemas:
    Beheerder:
      type: object
      description: |-
        Generate a serializer out of a GegevensGroepType.

        Usage::

        >>> class VerlengingSerializer(GegevensGroepSerializer):
        ...     class Meta:
        ...         model = Zaak
        ...         gegevensgroep = 'verlenging'
        >>>

        Where ``Zaak.verlenging`` is a :class:``GegevensGroepType``.
      properties:
        naam:
          type: string
          description: De naam van de beheerder van dit tabel.
          maxLength: 200
        email:
          type: string
          format: email
          title: Mail
          description: De email van de beheerder van dit tabel.
          maxLength: 254
        afdeling:
          type: string
          description: De afdelings naam van de beheerder van dit tabel.
          maxLength: 200
        organisatie:
          type: string
          description: De organisatie naam van de beheerder van dit tabel.
          maxLength: 200
    Item:
      type: object
      properties:
        code:
          type: string
          description: De unique code (per tabel) van het item.
          maxLength: 36
        naam:
          type: string
          description: De naam van het item.
          maxLength: 200
        begindatumGeldigheid:
          type: string
          format: date-time
          nullable: true
          description: De datum vanaf deze tabel geldig is.
        einddatumGeldigheid:
          type: string
          format: date-time
          nullable: true
          description: De datum tot wanneer deze tabel geldig is.
        aanvullendeGegevens:
          nullable: true
          description: Extra gegevens die niet standaard gekoppeld zijn aan een item.
      required:
      - code
      - naam
    Tabel:
      type: object
      properties:
        code:
          type: string
          description: De unique code van het tabel.
          maxLength: 40
        naam:
          type: string
          description: De naam van het tabel.
          maxLength: 200
        beheerder:
          allOf:
          - $ref: '#/components/schemas/Beheerder'
          nullable: true
          description: De informatie van de beheerder van deze tabel.
        einddatumGeldigheid:
          type: string
          format: date-time
          nullable: true
          description: De datum tot wanneer deze tabel geldig is.
        items:
          allOf:
          - $ref: '#/components/schemas/Item'
          readOnly: true
      required:
      - code
      - items
      - naam
  securitySchemes:
    tokenAuth:
      type: apiKey
      in: header
      name: Authorization
      description: Token-based authentication with required prefix "Token"
