# Generated by Django 4.2.11 on 2024-04-25 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tabel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="De unique code van het tabel.",
                        max_length=40,
                        unique=True,
                        verbose_name="code",
                    ),
                ),
                (
                    "naam",
                    models.CharField(
                        help_text="De naam van het tabel.",
                        max_length=200,
                        verbose_name="naam",
                    ),
                ),
                (
                    "einddatum_geldigheid",
                    models.DateTimeField(
                        blank=True,
                        help_text="De datum tot wanneer deze tabel geldig is.",
                        null=True,
                        verbose_name="einddatum geldigheid",
                    ),
                ),
                (
                    "beheerder_naam",
                    models.CharField(
                        blank=True,
                        help_text="De naam van de beheerder van dit tabel.",
                        max_length=200,
                        null=True,
                        verbose_name="naam",
                    ),
                ),
                (
                    "beheerder_email",
                    models.EmailField(
                        blank=True,
                        help_text="De email van de beheerder van dit tabel.",
                        max_length=254,
                        null=True,
                        verbose_name="mail",
                    ),
                ),
                (
                    "beheerder_afdeling",
                    models.CharField(
                        blank=True,
                        help_text="De afdelings naam van de beheerder van dit tabel.",
                        max_length=200,
                        null=True,
                        verbose_name="afdeling",
                    ),
                ),
                (
                    "beheerder_organisatie",
                    models.CharField(
                        blank=True,
                        help_text="De organisatie naam van de beheerder van dit tabel.",
                        max_length=200,
                        null=True,
                        verbose_name="organisatie",
                    ),
                ),
            ],
            options={
                "verbose_name": "tabel",
                "verbose_name_plural": "tabellen",
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="De unique code (per tabel) van het item.",
                        max_length=36,
                        verbose_name="code",
                    ),
                ),
                (
                    "naam",
                    models.CharField(
                        help_text="De naam van het item.",
                        max_length=200,
                        verbose_name="naam",
                    ),
                ),
                (
                    "begindatum_geldigheid",
                    models.DateTimeField(
                        blank=True,
                        help_text="De datum vanaf waneer deze tabel geldig is.",
                        null=True,
                        verbose_name="begindatum geldigheid",
                    ),
                ),
                (
                    "einddatum_geldigheid",
                    models.DateTimeField(
                        blank=True,
                        help_text="De datum tot wanneer deze tabel geldig is.",
                        null=True,
                        verbose_name="einddatum geldigheid",
                    ),
                ),
                (
                    "aanvullende_gegevens",
                    models.JSONField(
                        blank=True,
                        help_text="Extra gegevens die niet standaard gekoppeld zijn aan een item.",
                        null=True,
                        verbose_name="aanvullende gegevens",
                    ),
                ),
                (
                    "tabel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.tabel",
                        verbose_name="tabel",
                    ),
                ),
            ],
            options={
                "verbose_name": "item",
                "verbose_name_plural": "items",
                "unique_together": {("tabel", "code")},
            },
        ),
    ]
