# Generated by Django 4.2.10 on 2024-05-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tabel",
            name="beheerder_afdeling",
            field=models.CharField(
                blank=True,
                help_text="De afdelings naam van de beheerder van dit tabel.",
                max_length=200,
                verbose_name="afdeling",
            ),
        ),
        migrations.AlterField(
            model_name="tabel",
            name="beheerder_naam",
            field=models.CharField(
                blank=True,
                help_text="De naam van de beheerder van dit tabel.",
                max_length=200,
                verbose_name="naam",
            ),
        ),
        migrations.AlterField(
            model_name="tabel",
            name="beheerder_organisatie",
            field=models.CharField(
                blank=True,
                help_text="De organisatie naam van de beheerder van dit tabel.",
                max_length=200,
                verbose_name="organisatie",
            ),
        ),
    ]
