name: Code quality checks

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches:
      - master
    paths:
      - "ruff.toml"
  pull_request:
    paths:
      - "ruff.toml"
  workflow_dispatch:

jobs:
  open-api-workflow-code-quality:
    uses: maykinmedia/open-api-workflows/.github/workflows/code-quality.yml@v5
    with:
      python-version: "3.12"
      node-version: "20"

      postgres-image: "postgres:17"

      django-settings-module: "referentielijsten.conf.ci"
