name: Code quality checks

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches:
      - master
    paths:
      - '**.py'
      - '**.yml'
  pull_request:
    paths:
      - '**.py'
      - '**.yml'
  workflow_dispatch:

jobs:
  open-api-workflow-code-quality:
    uses: maykinmedia/open-api-workflows/.github/workflows/code-quality.yml@v1
    with:
      python-version: '3.11'
      node-version: '18'

      postgres-image: 'postgres:15'

      django-settings-module: 'referentielijsten.conf.ci'
