name: generate-postman-collection

on:
  push:
    paths:
      - "src/referentielijsten/api/openapi.yaml"
      - ".github/workflows/generate-postman-collection.yml"
    branches:
      - '**'
  workflow_dispatch:

jobs:
  open-api-workflow-generate-postman-collection:
    uses: maykinmedia/open-api-workflows/.github/workflows/generate-postman-collection.yml@v1
    with:
      node-version: '18'
      schema-path: 'src/referentielijsten/api/openapi.yaml'
