name: generate-sdks

on:
  push:
    paths:
      - "src/referentielijsten/api/v*/openapi.yaml"
      - ".github/workflows/generate-sdks.yml"
    branches:
      - '**'
  workflow_dispatch:

jobs:
  open-api-workflow-generate-sdks:
    uses: maykinmedia/open-api-workflows/.github/workflows/generate-sdks.yml@initial-setup
    with:
      node-version: '18'
      schema-path: 'src/referentielijsten/api/openapi.yaml'
