name: lint-oas

on:
  push:
    paths:
      - "src/referentielijsten/api/v*/openapi.yaml"
      - .github/workflows/lint-oas.yml
    branches:
      - '**'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ 'v1' ]

    name: Run with version ${{ matrix.version }}

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install spectral
        run: npm install -g @stoplight/spectral@5
      - name: Run OAS linter
        run: spectral lint ./src/referentielijsten/api/openapi.yaml
