name: lint-oas

on:
  push:
    paths:
      - "src/referentielijsten/api/v*/openapi.yaml"
      - .github/workflows/lint-oas.yml
    branches:
      - '**'
  workflow_dispatch:

jobs:
  open-api-workflow-lint-oas:
    uses: maykinmedia/open-api-workflows/.github/workflows/lint-oas.yml@initial-setup
    with:
      node-version: '18'
      schema-path: 'src/referentielijsten/api/openapi.yaml'
