name: check-oas

on:
  push:
    paths:
      - "src/referentielijsten/api/*/openapi.yaml"
      - .github/workflows/oas-check.yml
    branches:
      - '**'
  workflow_dispatch:

jobs:
  open-api-workflow-check-oas:
    uses: maykinmedia/open-api-workflows/.github/workflows/oas-check.yml@v1
    with:
      python-version: '3.11'

      schema-path: 'src/referentielijsten/api/openapi.yaml'

      django-settings-module: 'referentielijsten.conf.ci'
